site_name: Strangelands Docs
theme:
  name: material
  palette:
    primary: white
    accent: blue grey
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  media: "(prefers-color-scheme: light)"
  scheme: default 
  toggle:
    icon: material/brightness-7
    name: Switch to dark mode


